feature_type: baseline
full_seq_len: 2048
datasplit: cross_dancer
windows: 300
cond_feadim: 35
fd_motion_dir: /data/lrh/datasets/fine_dance/origin/motion_feature319mirror
out_length: 30
render_dir: FineDance_test_renders/
mudic_feature_dir: /data2/lrh/dataset/fine_dance/div_by_time/music_25
keymotion_dir: ''
checkpoint: checkpoint.pt
nfeats: 139
music_dir: data/test/wavs
save_motions: true
fullpt: false
motion_save_dir: Adebug
cache_features: false
do_normalize: false
no_render: false
use_cached_features: false
feature_cache_dir: cached_features/
keystage: false
no_vloss: false
decoder_type: hrnet
scale: 8
hint: 0
hryaml: configs/hryaml.yaml
gpu: 0
mode: inpaint_soft
soft_hint: gpt
length1: 1024
length2: 256
gpt_window_size: 256
clip_frames: 4
checkpoint2: experiments/1023edge139_256_35/train/bce_fc2/weights/Full-train-3070.pt
nb_code: 1024
code_dim: 1024
output_emb_width: 1024
tk_dir: /data2/lrh/project/dance/long/experiments/vqvae/output_vq/clip8_139/FineDance_1007_1024_win128/eval_idx512
resume_trans: /data2/lrh/project/dance/long/experiments/vqvae/gpt/clip8_139/FineDance_1007_1024_win128/ckpt/mask_best_acc.pth
resume_pth: /data2/lrh/project/dance/long/experiments/vqvae/output_vq/clip8_139/FineDance_1007_1024_win128/vqvae/f_139/best_recon.pth
mu: 0.99
down_t: 2
stride_t: 2
width: 1024
depth: 3
dilation_growth_rate: 3
vq_act: relu
vq_norm: null
block_size: 2049
quantizer: ema_reset
embed_dim_gpt: 512
clip_dim: 512
num_layers: 2
n_head_gpt: 8
ff_rate: 4
drop_out_rate: 0.1
feature_dim: 139
