dataname:
- AISTPP_266
Norm: True
gpu: 2
window_size: 64
windows: 1
feature_dim: 266
tk_dir: /data2/lrh/dyq/debug_exp/dataset/data/tokenized/f_135/
full_seq_len: 128
mix: false
batch_size: 128
fd_music_dir: /data2/lrh/dyq/debug_exp/dataset/data/origin/music_feature35_edge
fd_motion_dir: /data2/lrh/dyq/debug_exp/dataset/data/origin/mofeature_vq
partial: full
aistpp_dir: /data2/lrh/human_datasets/aist_plusplus_final/
aistpp_p_dir: /data2/lrh/dyq/debug_exp/dataset/data/mofeatrue135/mofeature_aistpp/
p_h3d_dir: /data2/lrh/dyq/debug_exp/dataset/data/mofeatrue135/
h3d_texts_dir: /data2/lrh/dyq/debug_exp/dataset/data/HumanML3D/texts/
o_h3d_dir: /data2/lrh/dyq/debug_exp/dataset/data/HumanML3D/
total_iter: 200000
warm_up_iter: 1000
lr: 0.0002
lr_scheduler:
- 50000
- 400000
gamma: 0.05
weight_decay: 0.0
commit: 0.02
loss_vel: 1
recons_loss: l2
code_dim: 1024
nb_code: 1024
mu: 0.99
down_t: 2
stride_t: 2
width: 1024
depth: 3
dilation_growth_rate: 3
output_emb_width: 1024
vq_act: relu
vq_norm: null
quantizer: ema_reset
beta: 1.0
resume_pth: experiments/vqvae/AISTPP_266/mo266_0607_win64_Norm/vqvae/f_266_5710/best_recon.pth
resume_gpt: null
out_dir: experiments/vqvae/output_vq/
ckpt_dir: experiments/vqvae/ckpt
results_dir: visual_results/
visual_name: baseline
exp_name: experiments/vqvae/AISTPP_266/mo266_0607_win64_Norm
print_iter: 200
save_iter: 50
eval_iter: 1000
seed: 123
vis_gt: false
nb_vis: 20
