baseyaml: configs/EDGE_KeyDiff_Hrnet/base.yaml
batch_size: 512
checkpoint: ''
do_normalize: false
ema_interval: 1
epochs: 2000
exp_name: finedance_120
feature_type: baseline
full_seq_len: 120
hryaml: configs/EDGE_KeyDiff_Hrnet/hryaml.yaml
keystage: false
mix: false
nfeats: 319
no_vloss: false
project: experiments/finedance_120_dancer/train
render_dir: experiments/finedance_120_dancer/renders
save_interval: 10
scale: 8
wandb_pj_name: finedance
windows: 10
